# frozen_string_literal: true

source 'https://rubygems.org'

gem 'embulk', '< 0.10'
gem 'embulk-filter-expand_json'
gem 'embulk-input-bigquery'
source 'https://rubygems.pkg.github.com/st-tech' do
  gem 'embulk-output-elasticsearch'
end
